### ISSUE TITLE
Setting int parameters to action servers

### ISSUE THREAD

**Issue by RaresAmbrus** [strands-project/strands_executive#10]
Is it possible to add other type of arguments to the action lib goal, like ints ? The methods in `strands_executive_msg.task_utils` seem to be only for adding strings and ros messages.

For example, in the action:
https://github.com/strands-project/scitos_apps/blob/hydro-devel/scitos_ptu/action/PanTilt.action

the parameters are 6 ints.

**Comment by hawesie** [comment]
It should be a trivial extension. I'll see what I can do.

**Comment by RaresAmbrus** [comment]
Ok, thank you.

**Comment by hawesie** [comment]
@RaresAmbrus have a look at #11 and see if it works for you.

**Comment by RaresAmbrus** [comment]
Awesome, I think that should do it! I'll test it on the robot tomorrow morning. Thanks @hawesie

**Comment by RaresAmbrus** [comment]
@hawesie I tested this out and it works. Can you please merge your branch to the strands repository?
