### ISSUE TITLE
submodule not supported by bloom-release

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/strands_executive#104]
The PRISM submodule in here will not be release-able. Either we need to release it as a separate Debian package and rosdep-end on it, or (better option), it should be snap-shotted in here with `git subtree`

**Comment by bfalacerda** [comment]
can you give a short explanation on why you prefer the `git subtree`? I was thinking of going for the standalone debian package + rosdep, but I don't have an idea on what git subtree is.

**Comment by marc-hanheide** [comment]
check https://github.com/apenwarr/git-subtree/blob/master/git-subtree.txt

I can also help you doing it... just not now

**Comment by bfalacerda** [comment]
cheers. i'm not doing it just now anyway. i'll ask for help if/when i need it

**Comment by bfalacerda** [comment]
prism-robots is now a stand-alone apt-get package on which strands_executive depends
