### ISSUE TITLE
Task executor should retry actions after failure

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_executive#122]

**Comment by hawesie** [comment]
This was raised after the marathon, but never implemented. @marc-hanheide is this necessary for the care scenario? Currently if the task reports failure, or if navigation to the task reports failure, then the task is dropped as failed. My rationale for just failing is that monitored et al navigation are responsible for retrying the navigation, so having retries here would just be redundant. Also If a task itself reports failure then there's not a lot to do to fix it from this end (and it would probably be scheduled for execution straight away if added back to the scheduler after failure).

**Comment by marc-hanheide** [comment]
agreed. I don't think we need it...
