### ISSUE TITLE
Release of mdp_plan_executor

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_executive#129]
If we plan to use the mdp_plan_executor for the deployments (which I hope we will), we need to get it released. @bfalacerda what issues are holding this back?

**Comment by bfalacerda** [comment]
I need the new definitions of the topological map merged

**Comment by bfalacerda** [comment]
should i create a new package from scratch in hydro-release and start building up from there and then make a PR, or start from hydro-devel, and then try to merge both branches? I don't know if hydro-devel is too out-of-date to do it, so I'm more inclined for the first option

@hawesie, suggestions?

**Comment by hawesie** [comment]
I suggest starting from hydro-release. hydro-devel is out of date. Once you've got the mdp executor sorted we can scrap the old branch (perhaps renaming hydro-release to indigo-devel)

**Comment by hawesie** [comment]
Progress on this is needed soon please!

**Comment by bfalacerda** [comment]
the code is almost there, and then we need to test this, along with https://github.com/strands-project/strands_navigation/issues/181

I'm putting this on top of my list of priorities

**Comment by hawesie** [comment]
Thanks!

**Comment by hawesie** [comment]
Released.
