### ISSUE TITLE
strands_executive_msgs missing in in `build_depend`

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/strands_executive#138]
see https://lcas.lincoln.ac.uk/jenkins/job/ros-indigo-wait-action_binarydeb_trusty_amd64/1/console

```
CMake Error at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:75 (find_package):
  Could not find a package configuration file provided by
  "strands_executive_msgs" with any of the following names:

    strands_executive_msgsConfig.cmake
    strands_executive_msgs-config.cmake

```

**Comment by hawesie** [comment]
Nothing has changed in any of these packages! Could it be a Jenkins issue?

**Comment by marc-hanheide** [comment]
it has changed: https://github.com/strands-project/strands_executive/commit/c9113ab7f3b5976313dd0fc086241d35be664fff#diff-4df48e1e34b2737c8f2760f44fd0fd45 and that's what causes it.

**Comment by hawesie** [comment]
That was ages ago! I'll look.

**Comment by hawesie** [comment]
Ah, but this is the first time it's been released since those changes I guess.

**Comment by marc-hanheide** [comment]
yep
