### ISSUE TITLE
use full travel times to waypoint vector

### ISSUE THREAD

**Issue by bfalacerda** [strands-project/strands_executive#152]
The  GetExpectedTravelTimesToWaypoint is being called redundantly  because the vector it returns is not being used at the scheduler level.

The scheduler should use it better

**Comment by hawesie** [comment]
At my end I could consider epochs equivalent if they fall within a certain duration of each other. That would prevent me calling the travel time service for tasks that have execution times that are only seconds apart. Should I do that, or will you handle this as part of #154? My preference is that you handle it as then the caller can be ignorant of epoch window sizes.

**Comment by bfalacerda** [comment]
yes, i'll do it, i also think it makes more sense at the mdp level
