### ISSUE TITLE
ROS msg type to describe a launch file and resulting topics

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_executive#20]
Create a ROS msg type describing a run launch file plus the topics and services it must provide. This is required for #19.

**Comment by cburbridge** [comment]
I don't think we need a ROS message type for this. Why not add it in the
yaml file as I propose in
https://github.com/strands-project/strands_management/issues/52 ? I know
that you don't want to have the scheduler concerned about launch stuff, but
launching could still be an action. Just one that is not currently used for
scheduling.

**Comment by hawesie** [comment]
See #19 - I agree we should make launch actions. And I'm very happy for tasks to be instantiated from launch files. The msg type is necessary because we are putting the same launch information into two  places -- the task and the goal for the action server -- so it is cleaner to adopt a type which encodes this information in a fixed format.

**Comment by hawesie** [comment]
Created by @marc-hanheide
