### ISSUE TITLE
[gcal_routine] If no location given, create service is not called

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_executive#202]
If I got it right, in [here](https://github.com/strands-project/strands_executive/blob/hydro-release/gcal_routine/src/gcal_routine/tools.py#L164-L165) the start and end nodes are taken from the 'Where' field in the calendar. If this fails it jumps to the except block and never calls the create service of the task itself. Therefore, e.g. the location will be `''` (due to [this giving an empty string](https://github.com/strands-project/strands_executive/blob/hydro-release/gcal_routine/src/gcal_routine/tools.py#L164-L165)) and the scheduler will die, the max_duration cannot be set by the task, etc.

This leads to the walking_group failing if relying on providing the correct location from a walking_group config file. This can be easily prevented by giving a location but requires that the user knows which the right location is. For example the charging_task shouldn't require to specify that it is executed at the `ChargingPoint`; makes it a bit redundant to have charging and maintenance tasks which are both wait_tasks which you have to give a location anyway.

**Comment by hawesie** [comment]
The scheduler does not die on an empty string (or at least shouldn't), but should do the task where the robot is when the task is due for execution.
