### ISSUE TITLE
Publish IDs of dropped and completed tasks

### ISSUE THREAD

**Issue by gestom** [strands-project/strands_executive#217]
It would be nice if a task ID was published whenever a task is completed.
Similarly, it would be nice if a task ID was published whenever a task is dropped.

(Needed for AAF deployment).

**Comment by hawesie** [comment]
Yep! Do you have a rough deadline by when you'd like this?

**Comment by gestom** [comment]
Monday would be nice (sorry for that).

**Comment by hawesie** [comment]
Monday is difficult. I could probably guarantee it by the Friday after. It might be @mudrole1 could do it sooner?

**Comment by gestom** [comment]
I can also try it myself, if you give me hint where it could be in the code.

**Comment by hawesie** [comment]
I'm happy to try to get it in for Monday, but just not promise it.

The places to look are:

https://github.com/strands-project/strands_executive/blob/hydro-release/task_executor/scripts/scheduled_task_executor.py

and perhaps its superclass:

https://github.com/strands-project/strands_executive/blob/hydro-release/task_executor/src/task_executor/sm_base_executor.py

Also:

https://github.com/strands-project/strands_executive/blob/hydro-release/task_executor/src/task_executor/execution_schedule.py

**Comment by mudrole1** [comment]
I am now finishing something else, I can update you about my free time Wed evening.

**Comment by mudrole1** [comment]
The tasks are dropped in the file scheduled_task_executor.py in the method try_schedule line 426... Dropped tasks are kept in the list "dropped_tasks" so we need just publish this (or maybe just IDs)

About publishing the ID when a task is completed - Do you need the id after it is completed? I thought in our initial discussion, you need to get ID back when you create a new task...  
If you need completion, I need to have a deeper look where it is done

**Comment by hawesie** [comment]
@mudrole1 did you do anything on this? Now the IJCAI papers are done I can look.

**Comment by mudrole1** [comment]
Nope, sorry :-/ (as no one was urging I completely forgot about it )

**Comment by hawesie** [comment]
Ok, I’ll do it.

**Comment by gestom** [comment]
Hi, I just started to look into it, I think that I might have it done by Friday as part of planned infoterminal improvements.

**Comment by hawesie** [comment]
I’m literally looking at the code now. Let me know if you want me to add the change or leave it to you.

**Comment by gestom** [comment]
Go ahead then, thanks!

**Comment by hawesie** [comment]
When you say 'completed' do you care whether they succeeded or failed?

**Comment by hawesie** [comment]
Actually it doesn't matter as both are in there.

In the current system you can listen to the topic `/task_executor/events` which publishes `TaskEvent` messages. These messages have the task itself (including its id) and an event field. The event field is assigned based on the constants in the TaskEvent msg definition. To get an idea of what this gives you, run `rosrun task_executor task_status.py` and you'll get the events printed out as they occur.

**Comment by hawesie** [comment]
The above does task completion, but not dropping. I've added a new branch to this repo [publish_dropped_tasks](https://github.com/strands-project/strands_executive/tree/publish_dropped_tasks) which adds my initial attempt at publishing on dropped tasks. This publishes `TaskEvent` messages on dropping, and there is also `/task_executor/dropped` topic which has just the dropped tasks published on it. This is actually redundant give the event topic, so I'll probably remove this again. 

This branch works for the cases I can easily test, but I'm not 100% confident it covers all the cases of task dropping. If you could run this branch for your use cases and let me know if it does what you want, that would be great.

**Comment by hawesie** [comment]
@gestom please let me know how this works for you.
