### ISSUE TITLE
Visualising mdp navigation policies

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_executive#219]
Hey @bfalacerda or @Jailander how do I visualise the navigation policies in rviz?

**Comment by bfalacerda** [comment]
There should be some MarkerArray for it, with some descriptive name that I don't remember right now

**Comment by hawesie** [comment]
And is it enabled by default in the released code or do I need a special branch or config?

**Comment by bfalacerda** [comment]
I think it's enabled

**Comment by Jailander** [comment]
Hi, @hawesie I just saw this sorry sliped my eye, I think its currently not enabled, I'll make a PR solving this

**Comment by hawesie** [comment]
Closed via https://github.com/strands-project/strands_navigation/issues/292
