### ISSUE TITLE
Can't set execution to False

### ISSUE THREAD

**Issue by Jailander** [strands-project/strands_executive#223]
When trying to set execution to **False**, task execution refuses these are the service calls 

![Screenshot from werner](https://files.gitter.im/strands-project/aaf_deployment/bItB/blob)

and this is scheduler output:

![Screenshot from werner](https://files.gitter.im/strands-project/aaf_deployment/GBi2/blob)

**Comment by hawesie** [comment]
Ok, I'll look, but there's little chance of a fix happening this week.

**Comment by Jailander** [comment]
I thought so, I think we can manage for now
