### ISSUE TITLE
Do a task at one of multiple waypoints

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_executive#247]
If I want to have an action that happens at one of a set of waypoints (e.g. charging), is it enough just to change this

``` python
 action = MdpAction(name=action_name, 
                     action_server=task.action, 
                     waypoints=[task.start_node_id],
                     pre_conds=[StringIntPair(string_data=state_var_name, int_data=0)],
                     outcomes=[outcome])
```

to have a list of waypoints, provided that the goal is to have the action executed?

**Comment by bfalacerda** [comment]
that's the idea. It was tested long ago, so  let me know if there's some issue

**Comment by hawesie** [comment]
Thanks, I'll try it and see.
