### ISSUE TITLE
bug in mdp executor when no action post-conditions are specified

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_executive#258]
I tried to specify an mdp action outcome with no post-conditions (i.e. it left the state-variable unchanged) but this caused something to make PRISM upset.

**Comment by bfalacerda** [comment]
can you show me how you defined the outcome and what prism told you was upsetting it?

**Comment by hawesie** [comment]
https://github.com/strands-project/planning_tutorial/blob/indigo-devel/scripts/sweep_at_waypoints.py

with line 53 commented out.

**Comment by bfalacerda** [comment]
is it too bad requiring you to define that, even if you define it as the same state?

**Comment by hawesie** [comment]
It’s not the end of the world, but it feels ugly. I suspect this pattern (positive outcome changes state, negative does not) will reoccur in future apps.

**Comment by bfalacerda** [comment]
ok, it's not too hard to solve, I'll do it on Friday if that's alright

**Comment by hawesie** [comment]
There’s no rush.
