### ISSUE TITLE
executor should check travel time before opening window

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_executive#281]
currently travel time is assumed to happen within the window.

**Comment by gestom** [comment]
So what will happen if I submit a task that has start_after = 0, max_duration = 400 and end_before = 500 and the expected nav time will be 200 ? Is the task dropped ?

**Comment by hawesie** [comment]
It depends on the current time. If the current time is 0 then yes, as it's impossible to get to the location and do the task in the window. If the current time is -100 then it will not get dropped.

**Comment by hawesie** [comment]
(this was the case in the previous scheduler implementation too)

**Comment by gestom** [comment]
Would it be possible to have another task parameter called 'min_duration', which, if set to a nonzero value, would be used instead of max_duration for this window check?
