### ISSUE TITLE
Give task creator final control of gcal task

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_executive#286]
The lines from https://github.com/strands-project/strands_executive/blob/indigo-devel/gcal_routine/src/gcal_routine/tools.py#L185 onwards mean that the task creator code does not get final say over the task creation. How about the factory gets sent yaml plus a partially instantiated task and then it does the final edits to the task? (not an urgent thing!)

**Comment by marc-hanheide** [comment]
Can we make it so that the gcal_routine sets the missing values IF the factory didn't set them, ie. if for instance `start_after` is zero etc.?
