### ISSUE TITLE
task executor not getting correct expected times from mdp

### ISSUE THREAD

**Issue by bfalacerda** [strands-project/strands_executive#316]
this if condition seems to change the value given by the MDP:

https://github.com/strands-project/strands_executive/blob/kinetic-devel/task_executor/scripts/mdp_task_executor.py#L865

**Comment by hawesie** [comment]
That code is just grim. It doesn't do what I think it was supposed to. Or perhaps it does what it's supposed to do, but breaks other things.

**Comment by hawesie** [comment]
The fix is to just remove it I think

**Comment by bfalacerda** [comment]
i commented it out and it worked fine, so i agree with removing it
