### ISSUE TITLE
Monitor navigation time in base_executor.py

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_executive#45]
Get expected from from mdp service.

**Comment by hawesie** [comment]
Already added mdp time info in my fork.

**Comment by hawesie** [comment]
@BFALacerda will the expected time include the time take for recoveries etc.? In other words to I need to multiply expected time by number of attempts to allow monitored navigation a few attempts before preempting.

**Comment by bfalacerda** [comment]
the expected time includes recoveries, no need to multiply it by anything.

However, it's better to get the expected time from the feedback of the mdp execution action server itself, to avoid calculating the same thing twice (three times if you count the time the scheduler asks for it also). Furthermore, the action feedback also takes into account the possible extra time that the addition of forbidden nodes might introduce.  After the mdp execution action server is merged in I'll switch the service call with reading the action feedback, if you agree

**Comment by hawesie** [comment]
Ok, sounds good.

**Comment by hawesie** [comment]
Done
