### ISSUE TITLE
Merge in branches for sm executor and updated policy execution

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_executive#63]
I'm quite confused on the final state of what needs to be merged back in here from the working system at g4s. We have  https://github.com/strands-project/strands_executive/pull/59 so is it just this?

**Comment by bfalacerda** [comment]
i completely forgot about this open pull request and have been committing stuff that's not in the g4s working system meanwhile

Maybe the best option is to close #59, push the sm_executor branch you have running on bob somewhere and merge from it

**Comment by hawesie** [comment]
ok.

**Comment by hawesie** [comment]
Here's the push from Bob: https://github.com/strands-project/strands_executive/pull/64

Does that look ok to merge?

**Comment by bfalacerda** [comment]
looks good yes
