### ISSUE TITLE
make mdp queries and execution thread safe

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_executive#65]
Queries to the navigation mdp while execution is happening causes errors. This needs to be fixed so that the robot can execute policies independent of queries being received.

**Comment by hawesie** [comment]
@BFALacerda 

In `def travel_time_to_node_cb(self,req)` you have the following lines:

``` python
        self.top_map_mdp.set_initial_state_from_name(starting_node)
        self.update_current_top_mdp(req.time_of_day,self.mdp_prism_file)
```

Are they actually necessary to respond to the query?

**Comment by bfalacerda** [comment]
yes, PRISM reads the models from text files and this is needed to update the initial state in the text file

**Comment by hawesie** [comment]
Ok, I understand it now.

So then I think the safest thing to do is refactor the node to create an object which wraps up an instance of TopMapMdp with a PrismClient so that we can have two instances of this object, one for querying and one for execution. We will then need to make sure both instances are updated when new information/times of day come in. We'd need to make the PrismClient port and and directory configurable so these don't get conflicted between instances.

Would that work?

**Comment by bfalacerda** [comment]
I was thinking of  creating an MDPExecutor class with its own PrismClient, TopMapMdp and ProductMdp instances, and do what you're saying there. Then we would have a mdp_planner node used by the scheduler, and  a mdp_executor node used by the task executor. I don't have a real preference there though, so if you prefer your solution we can go for it. Both solutions require having a configurable port and directory for the PrismClient

**Comment by hawesie** [comment]
You’re the expert here, so it’s your call! I think we should get this sorted early next week though if we can.

**Comment by bfalacerda** [comment]
ok, it's doable by then

**Comment by hawesie** [comment]
How’s this going?

**Comment by bfalacerda** [comment]
I've been sidetracked by other issues, I'm putting my full attention on this now, should be ready tomorrow. Sorry about the delay...

**Comment by bfalacerda** [comment]
see #66. I ended up following @hawesie 's suggestion, less messy for now

**Comment by bfalacerda** [comment]
closing old solved issue
