### ISSUE TITLE
Create meta-package

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_executive#80]

**Comment by hawesie** [comment]
Asked for by @cdondrup  too. @mudrole1 are you able to do this as part of your current work?

**Comment by cdondrup** [comment]
Didn't see this one. Was late yesterday.

**Comment by mudrole1** [comment]
Can you please point out, what it means?

**Comment by cdondrup** [comment]
@marc-hanheide posted a nice description here: https://github.com/strands-project/fremen/issues/13#issuecomment-90843485
