### ISSUE TITLE
continuous_patrolling.py not working

### ISSUE THREAD

**Issue by OMARI1988** [strands-project/strands_executive#81]
Hi,

I followed the instructions in here to run the continuous patrolling after I mapped the lab and inserted the topological waypoints into mongodb:

https://github.com/strands-project/strands_executive

but it doesn't work, it gives an error like this in task-scheduler.launch,

any advice ?

Cheers,
Muhannad
# 

strands@strands-Mi956:~$ roslaunch task_executor task-scheduler.launch topological_map:=cs_lab_1
... logging to /home/strands/.ros/log/5947f234-3cd9-11e4-9889-843a4b7f0ffc/roslaunch-strands-Mi956-32634.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://strands-Mi956:60831/
# SUMMARY

PARAMETERS
- /rosdistro
- /rosversion

NODES
  /
    mdp_planner (mdp_plan_exec/mdp_planner.py)
    schedule_server (scheduler/scheduler_node)
    scheduled_task_executor (task_executor/scheduled_task_executor.py)
    wait_node (wait_action/wait_node.py)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[mdp_planner-1]: started with pid [32659]
process[schedule_server-2]: started with pid [32666]
process[scheduled_task_executor-3]: started with pid [32667]
[ INFO] [1410797679.469792160]: Writing scheduling problems to mongodb_store
[ INFO] [1410797679.480302725]: Ready to serve schedules
process[wait_node-4]: started with pid [32696]
[INFO] [WallTime: 1410797679.949624] Waiting for services...
[INFO] [WallTime: 1410797679.960500] Done
[INFO] [WallTime: 1410797679.961069] Waiting for services...
[INFO] [WallTime: 1410797679.970173] Done
[INFO] [WallTime: 1410797679.970509] Waiting for /mdp_plan_exec/get_expected_travel_time_to_node
[WARN] [WallTime: 1410797685.266191] No data for edge between waypoints ChargingPoint and WayPoint1. Assuming it to be 20 seconds. Expected time between nodes will not be correct.
[WARN] [WallTime: 1410797685.266453] No data for edge between waypoints WayPoint1 and ChargingPoint. Assuming it to be 20 seconds. Expected time between nodes will not be correct.
[WARN] [WallTime: 1410797685.266613] No data for edge between waypoints WayPoint1 and WayPoint2. Assuming it to be 20 seconds. Expected time between nodes will not be correct.
[WARN] [WallTime: 1410797685.266967] No data for edge between waypoints WayPoint2 and WayPoint1. Assuming it to be 20 seconds. Expected time between nodes will not be correct.
Exception in thread "main" java.lang.NullPointerException
    at prism.PrismManager.main(PrismManager.java:222)
Traceback (most recent call last):
  File "/opt/strands/strands_catkin_ws/src/strands_executive/mdp_plan_exec/scripts/mdp_planner.py", line 502, in <module>
    mdp_planner =  MdpPlanner(sys.argv[1])
  File "/opt/strands/strands_catkin_ws/src/strands_executive/mdp_plan_exec/scripts/mdp_planner.py", line 37, in **init**
    self.policy_handler=PrismMdpManager(8086,'policy',top_map)
  File "/opt/strands/strands_catkin_ws/src/strands_executive/mdp_plan_exec/src/mdp_plan_exec/prism_mdp_manager.py", line 20, in **init**
    self.prism_client=PrismClient(port, self.directory)
  File "/opt/strands/strands_catkin_ws/src/strands_executive/mdp_plan_exec/src/mdp_plan_exec/prism_client.py", line 30, in **init**
    self.sock.connect((HOST, PORT))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(_args)
socket.error: [Errno 111] Connection refused
[mdp_planner-1] process has died [pid 32659, exit code 1, cmd /opt/strands/strands_catkin_ws/src/strands_executive/mdp_plan_exec/scripts/mdp_planner.py cs_lab_1 __name:=mdp_planner __log:=/home/strands/.ros/log/5947f234-3cd9-11e4-9889-843a4b7f0ffc/mdp_planner-1.log].
log file: /home/strands/.ros/log/5947f234-3cd9-11e4-9889-843a4b7f0ffc/mdp_planner-1_.log

**Comment by bfalacerda** [comment]
There are some prism processes that weren't killed properly and are using the ports. do `ps -ef | grep prism`and kill all the prism processes. That should do the trick.

This only happens when the process doesn't start properly, probably because you gave it a wrong topological map name on the first try. That's a problem I'll take care of next month, I know it's pretty annoying

**Comment by hawesie** [comment]
I also don't think the continuous patrolling setup will work as the code has decayed a little bit since it was first written. You should still be able to add tasks to visit waypoints though.

**Comment by OMARI1988** [comment]
Ok, tasks to visit waypoints is working.

Thanks
