### ISSUE TITLE
cannot find -lmessage_store

### ISSUE THREAD

**Issue by ToMadoRe** [strands-project/strands_executive#83]
This is due to 

```
target_link_libraries(cloud_merge
   ${catkin_LIBRARIES}
   ${PCL_LIBRARIES}
   ${QT_LIBRARIES}
   ${Boost_LIBRARIES}
   mongoclient
   message_store
 )
```

, which is in the CMakeLists.txt files of `cloud_merge` and `semantic map`

As @marc-hanheide mentioned on Gitter, explicitly linking the message_store is wong:
"that should already be resolved via ${catkin_LIBRARIES}
if the mongodb_store_cpp_clientis defined as a required dep in find_package(catkin REQUIRED COMPONENTS ... mongodb_store_cpp_client)
and we see it is, so just remove the last two lines from the target_link_libraries(cloud_merge… block
"

Also there is something wrong with the Boost Libraries, which is probably due to a missing dependency in `mongodb_store_cpp_client`.

Could the maintainer please fix this?

**Comment by marc-hanheide** [comment]
this works now
